---
title: "Heatmap"
output: html_document
date: "2023-10-16"
---

```{r}
library(pheatmap)
library(dplyr)
```
#load data

```{r}
DDP <- read.csv("gene_locationsV4.csv", row.names = 1)
```

#change TRUE/FALSE to 1/0 and re add rownames

```{r}
DDPH <- sapply(DDP, as.integer)
DDPH <- as.data.frame(DDPH)
rownames(DDPH) <- rownames(DDP)

```

#plotting heatmap

```{r}
plot1 <- pheatmap(DDPH)
#plot2 <- pheatmap(DDPH,cluster_cols = FALSE)
#plot3 <- pheatmap(DDPH,cluster_rows = FALSE)
#plot4 <- pheatmap(DDPH,cluster_cols = FALSE, cluster_rows = FALSE)

```

#plot heatmap but with columns and rows switched

```{r}
plot5 <- pheatmap(t(DDPH),fontsize_col = 3)
```

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(R.utils)
```


#heatmap example



```{r}
#pheatmap(DE_m_vs_tm20, annotation_col = HmapIDs, show_colnames=F, main = "Top DE genes Upreg")

```

```{r}
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

```
```{r}
levels(pbmc)
diffexp <- FindMarkers(pbmc, ident.1 = "pbmc3k", ident.2 = NULL, only.pos = TRUE)
```



```{r}
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
FetchData(pbmc, vars = all.genes)
```

