---
title: "New Visualisation"
output: html_document
date: "2023-10-19"
---


```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(R.utils)
library(pheatmap)
library(UpSetR)
```



```{r}
DDP <- read.csv("gene_locationsV4.csv", row.names = 1)
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
```


```{r}
DoHeatmap(pbmc, group)
```



```{r}
Difexp <- FetchData(pbmc, vars = all.genes)
Difexp
```

```{r}
DDPH <- sapply(DDP, as.integer)
DDPH <- as.data.frame(DDPH)
rownames(DDPH) <- rownames(DDP)
```

```{r}
upset(DDPH, nsets = 22,order.by = "freq")
```


```{r}
pbmc@assays$RNA@counts
```

```{r}

head(pbmc[["RNA"]][[]])


```

